spring:
  application:
    name: patient-service

#  datasource:
#    url: jdbc:postgresql://localhost:5433/patient
#    username: asik
#    password: asik
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

server:
  port: 4000

logging:
  level:
    root: info
