services:
  postgres:
    container_name: patient_management_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: asik
      POSTGRES_PASSWORD: asik
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped

volumes:
  postgres: