spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route for /api/patients/** to patient-service
            - id: patient-service
              uri: http://localhost:4000
              predicates:
                - Path=/api/v1/patients/**
              filters:
                - JwtValidation

              # Route for /api/docs/patients to patient-service /v3/api-docs
            - id: api-docs-patient-route
              uri: http://localhost:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients,/v3/api-docs

            - id: auth-service-route
              uri: http://localhost:4005
              predicates:
                - Path=/api/auth/**

            - id: api-docs-auth-route
              uri: http://localhost:4005
              predicates:
                - Path=/api-docs/auth
              filters:
                 - RewritePath=/api-docs/auth,/v3/api-docs

server:
  port: 4004

auth:
  service:
    url: http://localhost:4005